workspace/config/routes.rb
Rails.application.routes.draw do
  devise_for :users

    root 'usuarios#index', as: 'home'

    get 'projetos' => 'projetos#index', as: 'projetos'
    get 'index' => 'usuarios#index'

    resources :usuarios
    resources :projetos

end

workspace/app/models/bug.rb
class Bug < ActiveRecord::Base

    belongs_to :projeto
end

workspace/app/models/projeto.rb
class Projeto < ActiveRecord::Base

    has_many :bugs
end

workspace/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  has_many :usuarios

end

workspace/app/models/usuario.rb
class Usuario < ActiveRecord::Base
    validates :name, presence: true, length:{minimum: 3}
    
    belongs_to :user
end

workspace/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

workspace/app/controllers/projetos_controller.rb
class ProjetosController < ApplicationController
    
    before_action :authenticate_user!
    
    def project
        @title = 'Projetos cadastrados';
        @content = 'lista de projetos';
    end
    
    def index
        @projs = Projeto.all
    end
    
    def show
        @proj = Projeto.find(params[:id])
    end
    
    def new
        @proj = Projeto.new
    end
    
    def create
    #render plain: params[:projeto].inspect
        
        @proj = Projeto.new(post_params)
        
        if(@proj.save)
            
            #slack_notifier.ping("Novo projeto adicionado: " + @proj.title)
            
            #if @proj.bug.length != 0
            #    bug_description = @proj.bug
            #end
            
            a_project_add = {
              fallback: "Atenção Aviso a todos sem exceção",
              text: "Everything looks peachy",
              color: "danger",
              author_name: current_user,
              title: "bug_description",
              title_link: "https://desafio-rafalsr.c9users.io/projetos"
            }
            
            notifier.post text: "Novo projeto adicionado: \n"+ "<https://desafio-rafalsr.c9users.io/projetos|Click here> for details!", attachments: [a_project_add] 
            
            
            redirect_to @proj
        else
            render 'new'
        end
    end
    
    def edit
        @bug = Projeto.find(params[:id]).bugs
        
        @proj = Projeto.find(params[:id])
    end
    
    def update
        @proj = Projeto.find(params[:id])
        
        if(@proj.update(post_params))
            redirect_to @proj
        else
            render 'edit'
        end
    end
    
    def destroy
        @proj = Projeto.find(params[:id])
        @proj.destroy
        
        redirect_to projetos_path
    end
    
    private def post_params
        params.require(:projeto).permit(:title, :description, :deadline, :bug_id)
        
    end
    
    private def slack_notifier
      #  Slack::Notifier.new "https://hooks.slack.com/services/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" do
      #     defaults channel: "#canal-rafael-lima", 
      #      username: "Rafael",
      #       attachments:[{
      #                      color: "good"
      #      }]
      #  end
    end
end

workspace/app/controllers/usuarios_controller.rb
class UsuariosController < ApplicationController
    
    before_action :authenticate_user!
    
    def index
        @users = Usuario.all
    end
    
    def show
        @post = Usuario.find(params[:id])
    end
    
    def new
        @post = current_user.usuarios.build
        #Usuario.new
    end
    
    def create
        #render plain: params[:usuario].inspect
        
        @post = current_user.usuarios.build(post_params)
        #Usuario.new(post_params)
        
        if(@post.save)
            redirect_to @post
        else
            render 'new'
        end
    end
    
    def edit
         @post = Usuario.find(params[:id])
    end
    
    def update
        @post = Usuario.find(params[:id])
        
        if(@post.update(post_params))
            redirect_to @post
        else
            render 'edit'
        end
    end
    
    def destroy
        @post = Usuario.find(params[:id])
        @post.destroy
        
        redirect_to usuarios_path
    end
    
    private def post_params
        params.require(:usuario).permit(:name, :email, :age, :password, :cargo)
        
    end
end

workspace/app/helpers/application_helper.rb
module ApplicationHelper
end

workspace/app/helpers/projetos_helper.rb
module ProjetosHelper
end

workspace/app/helpers/usuarios_helper.rb
module UsuariosHelper
end

workspace/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css' %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

<nav class="navbar navbar-default">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href=<%=home_path%>>Desafio</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Usuarios", usuarios_path %></li>
          </ul>
          <ul class="nav navbar-nav">
            <li><%= link_to "Projetos", projetos_path %></li>
          </ul>
          
          
          <%# if current_page?('/usuarios') %>
            <%#ul class="nav navbar-nav navbar-right-left">
              <li><%#= link_to "Criar", new_usuario_path %><%#/li>
            <%#/ul>
          <%# elsif  current_page?('/projetos')%>
            <%#ul class="nav navbar-nav navbar-right">
              <li><%= link_to "Criar", new_projeto_path %><%#/li>
            <%#/ul>
          <% end %>
          
          <% if user_signed_in? %>
             <ul class="nav navbar-nav navbar-right">
                <li><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
              </ul>
          <% else %>
              <ul class="nav navbar-nav navbar-right">
              <li><%= link_to "Sign up", new_user_registration_path %></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
              <li><%= link_to "Sign in", new_user_session_path %></li>
            </ul>
          <% end %>
           
            
        </div><!--/.nav-collapse -->
      </div>
    </nav>
    

    
<div class="container">
  
  <%= yield %>
</div>


</body>
</html>

workspace/app/views/projetos/edit.html.erb
<h1>Editar projeto</h1>

<%= form_for :projeto, url: projeto_path(@proj), method:  :PATCH do |f| %>
    <% if @proj.errors.any? %>
        <% @proj.errors.full_messages.each do |msg| %>
            <div class="alert alert-danger"><%= msg %></div>
        <% end %>
    <% end %>


<p>
    <%= f.label :Titule %><br>
    <%= f.text_field(:title, {:class => 'form-control'}) %>
</p>

<p>
    <%= f.label :Descrição %><br>
    <%= f.text_area(:description, {:class => 'form-control'}) %>
</p>

<p>
    <%= f.label :Prazo %><br>
    <%= f.date_field(:deadline, {:class => 'form-control'}) %>
</p>

<div class="panel panel-primary">
				<div class="panel-heading">
					<h3 class="panel-title">Bugs</h3>
					<span class="pull-right clickable"><i class="glyphicon glyphicon-chevron-up"></i></span>
				</div>
				<div class="panel-body">
				    
                    <ul>
                        <li>
                            <% @proj.bug_id do |bug| %>
                            <% bug.description %>
                            <% end %>
                        </li>
                    </ul>
                </div>
			</div>

<p>
    <%= f.submit({:class => 'btn btn-primary'}) %>
</p>
<% end %>

workspace/app/views/projetos/index.html.erb
<p>
    <h1>Projetos</h1>
    <%= link_to "Adicionar", new_projeto_path, :class => 'btn btn-success' %>
</p>

<% @projs.each do |proj| %>

    <div class="row">
        <div class="span6">
            <div class="well">
                <h3><%= proj.title%></h3>
                <p><%= proj.description %></p>
                <p><%= proj.deadline %></p>
                
                <%= link_to "detalhes", projeto_path(proj), :class => 'btn btn-default' %>
            </div>
        </div>
        <div class="span8">
            <div class="well">
                <div class="accordion-heading">
                    <a class="accordion-toggle"
                       data-toggle="collapse"
                       data-parent="#accordion2"
                       href="#collapseOne">Bugs</a>
                </div>
                <div id="collapseOne" class="accordion-body collapse">
                    <div class="span6">
                        <div class="well well-small">
                            <div class="accordion-toggle">
                                ...some BUG...
                            </div>
                        </div>
                    </div>
                    <div class="span2"></div>                            
                </div>
            </div>
        </div>
    </div>
        

    
<% end %>

workspace/app/views/projetos/new.html.erb
<h1>Adicionar projeto</h1>

<%= form_for :projeto, url: projetos_path do |f| %>
    <% if @proj.errors.any? %>
        <% @proj.errors.full_messages.each do |msg| %>
            <div class="alert alert-danger"><%= msg %></div>
        <% end %>
    <% end %>

<p>
    <%= f.label :Título %><br>
    <%= f.text_field(:title, {:class => 'form-control'}) %>
</p>

<p>
    <%= f.label :Descrição %><br>
    <%= f.text_area(:description, {:class => 'form-control'}) %>
</p>

<p>
    <%= f.label :Prazo %><br>
    <%= f.date_field(:deadline, {:class => 'form-control'}) %>
</p>

<p>
    <%= f.submit({:class => 'btn btn-primary'}) %>
</p>

<div class="panel panel-primary">
				<div class="panel-heading">
					<h3 class="panel-title">Bugs</h3>
					<span class="pull-right clickable"><i class="glyphicon glyphicon-chevron-up"></i></span>
				</div>
				<div class="panel-body">
				    
                    <a class="btn btn-default btn-select">
                        
                        <input type="hidden" class="btn-select-input" id="bug" name="bug_selection" value="bug" />
                        <span class="btn-select-value">Select a information</span>
                        <span class='btn-select-arrow glyphicon glyphicon-chevron-down'></span>
                        <ul>
                            <li>Resolved</li>
                            <li class="selected">Problem</li>
                            
                        </ul>
                    </a>
                    
                    <%= f.label :Descrição %><br>
                    <%= f.text_field(:bug, {:class => 'form-control'}) %>
                </div>
			</div>
<% end %>

workspace/app/views/projetos/project.html.erb
<h1>
    <%= @title %>
</h1>

<p>  <%= @content %></p>

workspace/app/views/projetos/show.html.erb
<h1><%= @proj.title %></h1>

<%= form_for :projeto, url: projeto_path do |f| %>

<p><%= f.label :Titulo %>          <%= @proj.title %></p>
<p><%= f.label :Descrição %>            <%= @proj.description %></p>
<p><%= f.label :Prazo %>          <%= @proj.deadline %></p>

<hr>

<% end %>
<%= link_to "edit", edit_projeto_path(@proj), :class => 'btn btn-default' %>

<%= link_to "Delete", projeto_path(@proj), 
                method: :delete,
                data: {confirm: 'Are you sure?'},
                :class => 'btn btn-danger' %>

workspace/app/views/usuarios/edit.html.erb
<h1>Edit usuario</h1>

<%= form_for :usuario, url: usuario_path(@post), method:  :patch do |f| %>
    <% if @post.errors.any? %>
        <% @post.errors.full_messages.each do |msg| %>
            <div class="alert alert-danger"><%= msg %></div>
        <% end %>
    <% end %>

<!--%= form_for :usuario, url: usuarios_path do |f| %-->
<p>
    <%= f.label :Nome %><br>
    <%= f.text_field(:name, {:class => 'form-control'}) %>
</p>

<p>
    <%= f.label :Idade %><br>
    <%= f.text_field(:age, {:class => 'form-control'}) %>
</p>

<p>
    <%= f.label :Email %><br>
    <%= f.text_field(:email, {:class => 'form-control'}) %>
</p>



<p>
    <%= f.label :Senha %><br>
    <%= f.text_field(:password, {:class => 'form-control'}) %>
</p>



<p>
    <%= f.label :Cargo %><br>
    <%= f.text_field(:cargo, {:class => 'form-control'}) %>
</p>

<p>
    <%= f.submit({:class => 'btn btn-primary'}) %>
</p>
<% end %>

workspace/app/views/usuarios/index.html.erb
<p>
    <h1>Usuarios Cadastrados</h1>
    <%= link_to "Adicionar", new_usuario_path, :class => 'btn btn-success' %>
</p>

<% @users.each do |user| %>
    <div class="well">
        <h3><%= user.name%></h3>
        <p><%= user.age %></p>
        <p><%= user.email %></p>
        <!--p> <%= user.password %> </p-->
        <p><%= user.cargo %></p>
        
        <%= link_to "detalhes", usuario_path(user), :class => 'btn btn-default' %>
    </div>
<% end %>

workspace/app/views/usuarios/new.html.erb
<h1>Adicionar usuario</h1>

<%= form_for :usuario, url: usuarios_path do |f| %>
    <% if @post.errors.any? %>
        <% @post.errors.full_messages.each do |msg| %>
            <div class="alert alert-danger"><%= msg %></div>
        <% end %>
    <% end %>

<p>
    <%= f.label :Nome %><br>
    <%= f.text_field(:name, {:class => 'form-control'}) %>
</p>

<p>
    <%= f.label :Idade %><br>
    <%= f.text_field(:age, {:class => 'form-control'}) %>
</p>

<p>
    <%= f.label :Email %><br>
    <%= f.text_field(:email, {:class => 'form-control'}) %>
</p>

<p>
    <%= f.label :Senha %><br>
    <%= f.text_field(:password, {:class => 'form-control'}) %>
</p>

<p>
    <%= f.label :Cargo %><br>
    <%= f.text_field(:cargo, {:class => 'form-control'}) %>
</p>

<p>
    <%= f.submit({:class => 'btn btn-primary'}) %>
</p>
<% end %>

workspace/app/views/usuarios/show.html.erb
<h1><%= @post.name %></h1>

<%= form_for :usuario, url: usuario_path do |f| %>

<p><%= f.label :Idade %>          <%= @post.age %></p>
<p><%= f.label :Email %>            <%= @post.email %></p>
<p><%= f.label :Cargo %>          <%= @post.cargo %></p>

<% if @post.user == current_user%>
    <p><%= f.label :Senha %>          <%= @post.password %></p>
<% end %>

<hr>

<% end %>
<%= link_to "edit", edit_usuario_path(@post), :class => 'btn btn-default' %>

<% if @post.user == current_user%>
    <%= link_to "Delete", usuario_path(@post), 
                method: :delete,
                data: {confirm: 'Are you sure?'},
                :class => 'btn btn-danger' %>
<% end %>